spring:
  profiles:
    active: dev

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.phrolova.gacha.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
