spring.application.name=gacha-backend
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=com.phrolova.controller
springdoc.default-flat-param-object=true
knife4j.enable=true
knife4j.production=false
